name: build and publish image to docker hub
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t lukewarmtemp/rob498:latest
      - name: push image to docker hub
        run: |
          docker push lukewarmtemp/rob498:latest